name: Build in Ubuntu 20.04

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ROS 2 ${{ matrix.ros2_distro }}
    runs-on: ubuntu-20.04
    container: px4io/px4-dev-ros2-${{ matrix.ros2_distro }}:2021-05-31
    strategy:
      matrix:
        ros2_distro: [foxy]
    steps:
    - uses: actions/checkout@v2
    - name: Disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: Enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: Add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: Tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: Install dependencies
      run: |
        # Set locale
        sudo apt update
        sudo apt install -y locales
        sudo locale-gen en_US en_US.UTF-8
        sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        export LANG=en_US.UTF-8
        # Setup ROS 2 sources
        sudo apt install -y curl gnupg2 lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add
        sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        # Install ROS 2 ${{ matrix.ros2_distro }} packages
        sudo apt update
        sudo apt install -y --no-install-recommends \
          ros-${{ matrix.ros2_distro }}-sensor-msgs \
          ros-${{ matrix.ros2_distro }}-visualization-msgs
        # Setup environment
        source /opt/ros/${{ matrix.ros2_distro }}/setup.bash
        # Install MAVSDK from source
        sudo apt install -y colordiff git
        git clone --recursive https://github.com/Auterion/MAVSDK.git -b main
        cd MAVSDK
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON -Bbuild/default -H.
        sudo cmake --build build/default --target install -j`nproc --all`
        sudo ldconfig
        # Install DBUS
        sudo apt install -y libdbus-glib-1-dev
        # Install Clang formatter
        sudo apt install -y clang-format-10
    - name: Create colcon workspace
      run: |
        unset ROS_DISTRO
        mkdir -p /tmp/colcon_ws/src
        cp -ar ${GITHUB_WORKSPACE} /tmp/colcon_ws/src/autopilot_manager
    - name: Fetch source dependencies
      run: |
        git clone https://gitlab.com/libeigen/eigen.git -b 3.3.9 /tmp/colcon_ws/src/eigen
        git clone git@github.com:Auterion/image_downsampler.git /tmp/colcon_ws/src/image_downsampler
        git clone git@github.com:Auterion/landing_mapper.git -b new-height-map /tmp/colcon_ws/src/landing_mapper
        git clone git@github.com:Auterion/landing_planner.git /tmp/colcon_ws/src/landing_planner
        git clone git@github.com:Auterion/px4_msgs.git /tmp/colcon_ws/src/px4_msgs
        git clone git@github.com:Auterion/timing_tools.git /tmp/colcon_ws/src/timing_tools
    - name: Check code formatting
      run: tools/check_code_format.sh
    - name: Build
      working-directory: /tmp/colcon_ws
      run: |
        source /opt/ros/${{ matrix.ros2_distro }}/setup.bash
        colcon build --event-handlers console_direct+
