name: Build/deb packaging for Skynode and other archs

on:
  push:
    branches:
      - 'main'
      - 'release/*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  packaging:
    name: "ROS 2 ${{ matrix.ros2_distro }} - ${{ matrix.arch }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ros2_distro: [foxy]
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v2
      - name: Fisable the keychain credential helper
        run: git config --global credential.helper ""
      - name: Enable the local store credential helper
        run: git config --global --add credential.helper store
      - name: Add credential
        run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
      - name: Tell git to use https instead of ssh whenever it encounters it
        run: 'git config --global url."https://github.com/".insteadof git@github.com:'
      - name: Process Github reference
        id: github_refs
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends \
            git \
            python3-pip \
            qemu-user-static
          sudo pip3 install ros_cross_compile
      - name: Configure workspace
        run: |
          unset ROS_DISTRO
          mkdir -p /tmp/colcon_ws/src
          cp -ar ${GITHUB_WORKSPACE} /tmp/colcon_ws/src/autopilot_manager/
      - name: Build & Packaging (autopilot_manager)
        run: |
          # Clone MAVSDK to be built from source
          git clone --recursive https://github.com/Auterion/MAVSDK.git -b develop /tmp/MAVSDK
          # Add COLCON_IGNORE to the MAVSDK dir so colcon doesn't build it
          touch /tmp/MAVSDK/COLCON_IGNORE
          # Run cross compilation
          ros_cross_compile /tmp/colcon_ws \
            --arch ${{ matrix.arch }} \
            --os ubuntu \
            --rosdistro ${{ matrix.ros2_distro }} \
            --custom-setup-script scripts/cross_compile_dependencies.sh \
            --custom-data-dir /tmp/MAVSDK
      - name: Build zip
        run: |
          cd /tmp/colcon_ws/
          mv install_${{ matrix.arch }} install
          git fetch --all --tags
          TAG_VERSION=$(bash -c 'if [ $(git show-ref --tags) ]; then echo \"$(git describe --always --tags $(git rev-list --tags --max-count=1) | sed 's/v\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1')\"; else echo 1.0.0; fi')
          zip -r autopilot_manager_${{ matrix.ros2_distro }}_$TAG_VERSION-1_${{ matrix.arch }}.zip install
      - name: Upload autopilot_manager_${{ matrix.ros2_distro }}_$TAG_VERSION-1_${{ matrix.arch }}.zip artefact
        uses: actions/upload-artifact@v2
        with:
          name: autopilot_manager_${{ matrix.ros2_distro }}_${TAG_VERSION}-1_${{ matrix.arch }}.zip
          path: /tmp/colcon_ws/autopilot_manager_${{ matrix.ros2_distro }}_$TAG_VERSION-1_${{ matrix.arch }}.zip
          retention-days: 2
      - name: Publish artefacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/colcon_ws/autopilot_manager_${{ matrix.ros2_distro }}_$TAG_VERSION-1_${{ matrix.arch }}.zip
          asset_name: autopilot_manager_${{ matrix.ros2_distro }}_$TAG_VERSION-1_${{ matrix.arch }}.zip
          tag: ${{ steps.github_refs.outputs.branch }}-${{ steps.github_refs.outputs.sha_short }}
          overwrite: true
