name: Build/deb packaging for Skynode and other archs

on:
  push:
    branches:
      - 'main'
      - 'release/*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  packaging:
    name: "ROS 2 ${{ matrix.ros2_distro }} - ${{ matrix.arch }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ros2_distro: [foxy, galactic]
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v2
      - name: Fisable the keychain credential helper
        run: git config --global credential.helper ""
      - name: Enable the local store credential helper
        run: git config --global --add credential.helper store
      - name: Add credential
        run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
      - name: Tell git to use https instead of ssh whenever it encounters it
        run: 'git config --global url."https://github.com/".insteadof git@github.com:'
      - name: Process Github reference
        id: refs
        run: |
          git fetch --all --tags
          TAG_VERSION=$(bash -c " \\
            if [ \"$(git show-ref --tags)\" ]; then \\
              tag=$(git describe --always --tags $(git rev-list --tags --max-count=1) | sed -n 's/v\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/p'); \\
              if [[ -z \$(echo $tag | xargs) ]]; then \\
                echo 1.1.3; \\
              else \\
                echo $tag; \\
              fi; \\
            else \\
              echo 1.1.3; \\
            fi"
          )
          ARCH=$(bash -c "if [ \"${{ matrix.arch }}\" = \"x86_64\" ]; then echo amd64; elif [ \"${{ matrix.arch }}\" = \"aarch64\" ]; then echo arm64; fi")
          echo "::set-output name=tag_version::${TAG_VERSION}"
          echo "::set-output name=package_arch::${ARCH}"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M%S')"
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends \
            git \
            python3-pip \
            qemu-user-static
          sudo pip3 install ros_cross_compile
      - name: Configure workspace
        run: |
          unset ROS_DISTRO
          mkdir -p /tmp/colcon_ws/src
          cp -ar ${GITHUB_WORKSPACE} /tmp/colcon_ws/src/autopilot_manager/
      - name: Build & Packaging (autopilot_manager)
        run: |
          # Clone MAVSDK to be built from source
          git clone --recursive https://github.com/Auterion/MAVSDK.git -b main /tmp/MAVSDK
          # Add COLCON_IGNORE to the MAVSDK dir so colcon doesn't build it
          touch /tmp/MAVSDK/COLCON_IGNORE
          # Add source dependencies
          git clone https://gitlab.com/libeigen/eigen.git -b 3.3.9 /tmp/colcon_ws/src/eigen
          git clone git@github.com:Auterion/image_downsampler.git /tmp/colcon_ws/src/image_downsampler
          git clone git@github.com:Auterion/landing_mapper.git -b develop /tmp/colcon_ws/src/landing_mapper
          git clone git@github.com:Auterion/px4_msgs.git -b develop /tmp/colcon_ws/src/px4_msgs
          # Run cross-compilation
          ros_cross_compile /tmp/colcon_ws \
            --arch ${{ matrix.arch }} \
            --os ubuntu \
            --rosdistro ${{ matrix.ros2_distro }} \
            --custom-setup-script scripts/cross_compile_dependencies.sh \
            --custom-data-dir /tmp/MAVSDK \
            --skip-rosdep-keys Eigen3 image_downsampler landing_mapper px4_msgs px4_ros_com \
            --colcon-defaults /tmp/colcon_ws/src/autopilot_manager/scripts/packaging/defaults.yaml
      - name: Create zip
        run: |
          cd /tmp/colcon_ws/install_${{ matrix.arch }}
          rm -rf px4_msgs px4_ros_com # we don't need the px4_msgs and px4_ros_com packaged here
          zip -r autopilot-manager_${{ matrix.ros2_distro }}_v${{ steps.refs.outputs.tag_version }}_${{ steps.refs.outputs.package_arch }}.zip .
      - name: Publish artefacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/colcon_ws/install_${{ matrix.arch }}/autopilot-manager_${{ matrix.ros2_distro }}_v${{ steps.refs.outputs.tag_version }}_${{ steps.refs.outputs.package_arch }}.zip
          release_name: v${{ steps.refs.outputs.tag_version }}
          asset_name: autopilot-manager_${{ matrix.ros2_distro }}_v${{ steps.refs.outputs.tag_version }}_${{ steps.refs.outputs.package_arch }}.zip
          tag: v${{ steps.refs.outputs.tag_version }}
          overwrite: true
