name: Check code style

on:
  push:
    branches:
      - 'master'
      - 'v[0-9]+*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_code_style:
    name: Check code style
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Check code style
      run: tools/check_code_format.sh
